### ISSUE TITLE
AD56X8 could be converted and used for the AD568X parts without too much work?

### ISSUE THREAD

**Issue by paulvee** [RobTillaart/AD568X#2]
Hi Rob,
Your library for the AD56X8 devices seems to be very close to the AD568X family of devices.
They are the AD5681R, 2R, 3R and 3. Then there is also the AD5680 which is a more simple variant of the 1, 2 and 3 family.

I have the AD5680 parts that I want to use so I could test and verify the library. Unfortunately, modifying and/or extending your library is way beyond my skills.

Are you interested?
Regards,
Paul

**Comment by RobTillaart** [comment]
Thanks for your request.
I have to dive into the datasheets to see the differences in detail.
Maybe I can check those this week.
From previous work I know that most often one better start from a fresh copy.
 
Rob

**Comment by RobTillaart** [comment]
Had a quick look at the datasheets:
Am I correct it are all 1 channel DAC's with resolution 12,14,16,18 bit?

**Comment by RobTillaart** [comment]
AD5680 is a "breaking" one as it needs a 32 bit value, the others fit in 16 bit. 
Means communication is slightly different.
So focus in first iteration will be on the AD5681R, 2R, 3R and 3.

**Comment by RobTillaart** [comment]
OK, gave it a try here - https://github.com/RobTillaart/AD568X/tree/develop
Stripped the AD56X8 lib, removed and renamed and a lot TODO's are still there.
Not all functionality is supported (esp control register things).
AD5680 needs its own class (or at least more attention)
AD5681 short write is not supported (yet).
However the code compiles and looks like a starting point.

As I have no hardware, please give the develop branch a try and post feedback in a new issue under that repo.

**Comment by RobTillaart** [comment]
Think we can continue the discussion under the AD568X repo, so I will move this thread.

**Comment by paulvee** [comment]
Great work Rob, and blindingly fast to boot.
Thank you!
It will take me some time to go through the code.
Unfortunately, I only have the AD5680 ready to be tested.
Hopefully someone else has the other versions and is willing to contribute.

**Comment by RobTillaart** [comment]
I'll try to find some time today to make a dedicated AD5680 class.

**Comment by paulvee** [comment]
That would be fantastic!

**Comment by paulvee** [comment]
Rob,
I just found this library : https://github.com/PatrickBaus/AD568xR/tree/master

**Comment by RobTillaart** [comment]
Thanks, always interested to learn how others solved things.
Quick tech look, will work as I recognize the code.
It has some optimizations for ARM and TEENSYDUINO. No support for the AD5680 however.

**Comment by RobTillaart** [comment]
From the specs of the AD5680 I think you could address it as an AD5683 and the setValue() function.
The control register is NOT compatible.

**Comment by RobTillaart** [comment]
@paulvee 

Hi Paul, 
Stripped the library to get an AD5680 version.
Please check - https://github.com/RobTillaart/AD5680/tree/develop

**Comment by RobTillaart** [comment]
@paulvee 

I close this issue, feel free to reopen if needed.
